### ISSUE TITLE
Confirm data atation

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G4#10]
I am letting each group know that we will be using Bermuda data. is that ok? @Mosaddeq107 @JustinJaniszewski

**Comment by Mosaddeq107** [comment]
> I am letting each group know that we will be using Bermuda data. is that ok? @Mosaddeq107 @JustinJaniszewski

Before we make a decision, I think we need to do some trial and error plotting to see which dataset is easy to handle.

**Comment by sharmistharanit** [comment]
Ok. Sounds good.

**Comment by Mosaddeq107** [comment]
@sharmistharanit I have no problem using Bermuda triangle, but the Dataset-14 gives a better graphical output. We can choose this one if you want. (https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_brw_surface-flask_1_ccgg_month.txt)

**Comment by sharmistharanit** [comment]
What do you mean by better graphical output?
