### ISSUE TITLE
Conversation

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G4#11]
I saw that we have to have 30 conversations. How will check that? Any help will be appreciated. @Mosaddeq107 @JustinJaniszewski

**Comment by Mosaddeq107** [comment]
> I saw that we have to have 30 conversations. How will check that? Any help will be appreciated. @Mosaddeq107 @JustinJaniszewski

I think you can't count it automatically. Take track of your conversation.

**Comment by reshnashrestha** [comment]
The main motive of keeping points for conversation is that it increases our interaction.

**Comment by sharmistharanit** [comment]
Thanks for letting me know. @Mosaddeq107
