### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G4#2]
Who wants to be maintainer?

**Comment by JustinJaniszewski** [comment]
I'm fine with whoever being maintainer. If one of you would rather be maintainer then go for it. If not I wouldn't mind being it either.

**Comment by Mosaddeq107** [comment]
I have no issue if you want to be a maintainer 

> I'm fine with whoever being maintainer. If one of you would rather be maintainer then go for it. If not I wouldn't mind being it either.

**Comment by sharmistharanit** [comment]
ok sure.
