### ISSUE TITLE
Github Action

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework5G4#20]
Do we need to create github action only for the unit test and linting?

**Comment by Mosaddeq107** [comment]
> Do we need to create github action only for the unit test and linting?

Yes, AFIK.

**Comment by Mosaddeq107** [comment]
Update: Since there is already a unit testing Action added by the Professor, we have to add the lining workflow only and reuse the unit test Action that is already added.

**Comment by tirthbha** [comment]
@Mosaddeq107 Got you.
