### ISSUE TITLE
Task 1 file format

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G4#22]
Should the file be in py format? Or ipynb works fine for task 1? @laserlab

**Comment by Mosaddeq107** [comment]
As we need to employ Action Workflow for the unit testing, we have to use the py format. Dr. Tim can answer the best

**Comment by laserlab** [comment]
@Mosaddeq107 is right py is easier for unit testing and limiting in actions

**Comment by Mosaddeq107** [comment]
> @Mosaddeq107 is right py is easier for unit testing and limiting in actions

Thank you, Professor, for the confirmation.
