### ISSUE TITLE
Function for peak frequency

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G4#23]
Which function are you going to apply for calculating the peak frequency(ies)?

**Comment by Mosaddeq107** [comment]
@sharmistharanit 
Can answer the best

**Comment by tirthbha** [comment]
> Which function are you going to apply for calculating the peak frequency(ies)?

Same question.

**Comment by reshnashrestha** [comment]
I have used heavyside but I'm not sure if I did correctly or not.

**Comment by reshnashrestha** [comment]
I have used scipy.signal and  imported find_peaks
