### ISSUE TITLE
Maintainer 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G4#26]
Hi, @JustinJaniszewski 
Are you appointed as a maintainer? I posted on the discord to be a maintainer, but I assume that I have yet to be appointed as a maintainer of this group so far.

**Comment by JustinJaniszewski** [comment]
I don't believe I am the maintainer

**Comment by Mosaddeq107** [comment]
> I don't believe I am the maintainer

Okay,
I assumed that as well.
