### ISSUE TITLE
Dataset Selection 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G4#27]
Hi @sharmistharanit and  @JustinJaniszewski, we need to select a convenient dataset for our homework. Did you guys test the datasets to find a suitable one?

**Comment by JustinJaniszewski** [comment]
I was using the Bermuda data as we discussed but I don't think its too difficult to change at anytime.

**Comment by sharmistharanit** [comment]
We are using Bermuda data.
