### ISSUE TITLE
Milestone creation 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G4#28]
We need to create two milestones and should work to meet those milestones. 
What could be the name of those and their deadlines? 

@sharmistharanit 
@JustinJaniszewski

**Comment by JustinJaniszewski** [comment]
you could make one to put our task selection and maintainer stuff in. In the past I have liked calling it "Getting Started". You could also do milestones for Task 1, task 2, task 3

**Comment by Mosaddeq107** [comment]
> you could make one to put our task selection and maintainer stuff in. In the past I have liked calling it "Getting Started". You could also do milestones for Task 1, task 2, task 3

Thanks for the suggestions.
