### ISSUE TITLE
Found a suitable dataset. 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G4#29]
I tested many of the datasets available on the website and found the [dataset number 14 BRW](https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_brw_surface-flask_1_ccgg_month.txt) suitable and amenable.
Can you guys check this dataset's behaviors and comment on it?

**Comment by Mosaddeq107** [comment]
@JustinJaniszewski Can you have a look at this dataset?

**Comment by tirthbha** [comment]
Have you guys got the frequency values for the chosen data set?

**Comment by poojashresthacode** [comment]
@Mosaddeq107 How to know that certain data is good to take? Is there any idea?

**Comment by sharmistharanit** [comment]
I have the same question as Pooja, @Mosaddeq107
