### ISSUE TITLE
Accept merge request please

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework5G4#30]
@Mosaddeq107 if youre maintainer by the time you read this message could you accept my merge request. Its the start of my task. Thank you.

**Comment by Mosaddeq107** [comment]
@JustinJaniszewski 
I still need to become a maintainer. I informed Dr. Tim about that.

**Comment by Mosaddeq107** [comment]
Once

> @Mosaddeq107 if youre maintainer by the time you read this message could you accept my merge request. Its the start of my task. Thank you.

Once I become one, I will accept the merge request.

**Comment by sharmistharanit** [comment]
I saw your text in Discord. Did you not get access?

**Comment by JustinJaniszewski** [comment]
> Once
> 
> > @Mosaddeq107 if youre maintainer by the time you read this message could you accept my merge request. Its the start of my task. Thank you.
> 
> Once I become one, I will accept the merge request.

Alright, thank you
