### ISSUE TITLE
Unit Testing Action Workflow

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G4#31]
Hi all, as we need to create two unit testing (one for calculating the actual frequency and another for the peak frequency) py files, Can we do these two unit testings in **one single action workflow file** or add **two separate unit testing action workflow** files?

**Comment by sharmistharanit** [comment]
I would suggest opening one action flow file. You can change unit test file name in pytest workflow file.

**Comment by Mosaddeq107** [comment]
> I would suggest opening one action flow file. You can change unit test file name in pytest workflow file.

Thanks for your reply.

**Comment by uarif** [comment]
What if you use that code, which works for all .py files. I think that would make more sense, no?

**Comment by Mosaddeq107** [comment]
Okay. thanks
