### ISSUE TITLE
Data selection

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G4#4]
Which data will we use for our hw? any suggestion? @JustinJaniszewski @Mosaddeq107

**Comment by sharmistharanit** [comment]
can we work on the below-mentioned data?
St. Davids Head, Bermuda, United Kingdom (BME) data?

**Comment by JustinJaniszewski** [comment]
I'll take a look at your example when I can but I will say for now that our data should probably have a lot of points. I was trying to follow the example from the professor with a smaller data set and the fourier transform graph didn't look as nice.

**Comment by sharmistharanit** [comment]
Which data are we going to use finally? The deadline is near. @JustinJaniszewski @Mosaddeq107

**Comment by JustinJaniszewski** [comment]
I am using St. Davids Head, Bermuda, United Kingdom (BME) currently
