### ISSUE TITLE
Upload py format instead of ipynb (jupyter notebook) 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G4#42]
Hi, @JustinJaniszewski The file [fft.ipynb](https://github.com/Mosaddeq107/23-Homework5G4/blob/main/fft.ipynb) you uploaded is in Jupyter Notebook (ipynb) format. Since we need to do linting and unit testing, we need to upload the files in (py) format. Dr. Tim mentioned it in an issue.

**Comment by JustinJaniszewski** [comment]
Alright. thanks for letting me know. ill keep this issue open until I fix it
