### ISSUE TITLE
Is a licence required?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework5G4#43]
@Mosaddeq107 did you add the license because of a requirement or you just wanted to?

**Comment by sharmistharanit** [comment]
I think we need a license. I have seen group 1 has already made it.

**Comment by Mosaddeq107** [comment]
> @Mosaddeq107 did you add the license because of a requirement or you just wanted to?

It's not mandatory. However, Dr. Tim encouraged us to add a license for each homework.

**Comment by JustinJaniszewski** [comment]
Okay, thanks.
