### ISSUE TITLE
Please create milestones

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework5G4#44]
due date is coming up. I think we should start making milestones

**Comment by sharmistharanit** [comment]
Yes, you are right.

**Comment by Mosaddeq107** [comment]
> due date is coming up. I think we should start making milestones

Thanks for pointing out. 
However, I already created milestones.

**Comment by JustinJaniszewski** [comment]
Oh sorry then. It didn't show for me. Thanks anyway
