### ISSUE TITLE
Plot name

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G4#45]
I have seen your work. @JustinJaniszewski. You did not mention any plot names.

**Comment by sharmistharanit** [comment]
Also, you did not add the function for calculating actual frequency peak. @JustinJaniszewski

**Comment by JustinJaniszewski** [comment]
Good point. I will do that

**Comment by sharmistharanit** [comment]
Is it ok if you do task 2? I have done it already. don't need to do it again. @JustinJaniszewski

**Comment by JustinJaniszewski** [comment]
No problem
