### ISSUE TITLE
Question confusion

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G4#5]
What are we supposed to do to address the task (Write a function that calculates the actual frequency in useful units)? @Mosaddeq107 @JustinJaniszewski

**Comment by JustinJaniszewski** [comment]
so from what the professor was talking about in class, in his example we would get the frequency in units of like "1/months" I believe. But what does that mean? We want to convert the units into something we can understand intuitvely. I am not too familar at the moment with the assignment so I can't say for sure what the units should be.

**Comment by Mosaddeq107** [comment]
> so from what the professor was talking about in class, in his example we would get the frequency in units of like "1/months" I believe. But what does that mean? We want to convert the units into something we can understand intuitvely. I am not too familar at the moment with the assignment so I can't say for sure what the units should be.

I think you're right

**Comment by sharmistharanit** [comment]
I see.
