### ISSUE TITLE
Redistribution of Tasks

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G4#50]
Hi, @JustinJaniszewski, @sharmistharanit did task 1, and I will do Task 3. 
Can you please complete task 2 ASAP so that I can finish writing the documentation part?

**Comment by Pranjal-Srivastava-2023** [comment]
Have you completed the documentation?

**Comment by sharmistharanit** [comment]
Not yet. I am writing it. Thanks for reminding though.
