### ISSUE TITLE
Proper frequency unit

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G4#6]
What could be the proper frequency unit?

**Comment by Mosaddeq107** [comment]
Have you figured out that?

**Comment by reshnashrestha** [comment]
Not yet. What about you? 
Just got the hint but not sure that as data are collected each month may be 12 times per year.

**Comment by LinxuanHu** [comment]
month?

**Comment by reshnashrestha** [comment]
We chose cycles per month.
