### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G4#64]
I have seen one pull request in our repo. Can you merge it? @Mosaddeq107 
Also, I can't see any file regarding task 2. What's the file name?

**Comment by sharmistharanit** [comment]
@JustinJaniszewski

**Comment by Mosaddeq107** [comment]
> I have seen one pull request in our repo. Can you merge it? @Mosaddeq107 Also, I can't see any file regarding task 2. What's the file name?

Done

**Comment by JustinJaniszewski** [comment]
the file is merged now, its called fft_filter.ipynb

**Comment by sharmistharanit** [comment]
Yes I can see it now
