### ISSUE TITLE
Task 1 discussion 

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G4#7]
Who is doing task 1 in this group?

**Comment by Mosaddeq107** [comment]
@JustinJaniszewski will do that

**Comment by JustinJaniszewski** [comment]
can confirm.

**Comment by sharmistharanit** [comment]
I will be doing task 2

**Comment by reshnashrestha** [comment]
Oh okay. @JustinJaniszewski  have you started ?

**Comment by JustinJaniszewski** [comment]
No I have not

**Comment by tirthbha** [comment]
@Mosaddeq107 Who is doing task 2. I am expecting some assistance from you guys?

**Comment by reshnashrestha** [comment]
@JustinJaniszewski have you done task 1? which file format did you choose?

**Comment by JustinJaniszewski** [comment]
I have started it. I'm doing a jupyter notebook file if thats what you mean.

**Comment by reshnashrestha** [comment]
The task 1 by g1 can be seen under task1 folder in the main branch of group 1 main repo.
feedbacks are appreciated.
