### ISSUE TITLE
Lets make milestones

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework5G4#9]
@Mosaddeq107 if you are maintainer (or when you do become it) could you start making some milestones

**Comment by sharmistharanit** [comment]
Also, make some labels. It will be useful for our project. @Mosaddeq107

**Comment by Mosaddeq107** [comment]
> @Mosaddeq107 if you are maintainer (or when you do become it) could you start making some milestones

Yes. I am still not being appointed as a maintainer. Once Dr. Tim does that, I will make mile stones.

**Comment by Mosaddeq107** [comment]
> Also, make some labels. It will be useful for our project. @Mosaddeq107

Okay, I will make some new labels as well.

**Comment by sharmistharanit** [comment]
Ok. good.
